### ISSUE TITLE
Edit API request body field type selection box misplaced

### ISSUE THREAD

**Issue by veikai** [eolinker/postcat#123]
在API编辑页面选择字段类型时展开下拉框，后滚动页面，类型选择下拉框没有随页面滚动而变化位置

 - OS: [Windows_NT x64 10.0.22000]
 - Version [1.4.0-beta]
---
Expand the drop-down box when selecting the field type on the API editing page, and then scroll the page, the type selection drop-down box does not change position as the page scrolls

**Comment by scarqin** [comment]
@buqiyuan fork
