### ISSUE TITLE
API Test Response unicode show error

### ISSUE THREAD

**Issue by Cjwpython** [eolinker/postcat#142]
Before opening an issue, we recommend:
* Use English to communicate.
* Search for duplicates of [Issues](https://github.com/eolinker/eoapi/issues) and [Discussions](https://github.com/eolinker/eoapi/discussions) unresolved.

**Describe the bug**

**Desktop (please complete the following information):**
如果返回的json中包含了中文，在自定义部署的环境中会显示中文乱码

**Comment by scarqin** [comment]
@Cjwpython 方便截图描述一下详细的问题吗，need more info

**Comment by Cjwpython** [comment]
![image](https://user-images.githubusercontent.com/59188420/190189009-7ef1b924-dee3-4dba-a693-1bdea0fdd321.png)
我使用的python编写了一个demo,在请求之后，会有这个情况

**Comment by scarqin** [comment]
@Cjwpython Get,unicode 字符，我们考虑下怎么处理。

**Comment by Cjwpython** [comment]
试过了，没有用的
