### ISSUE TITLE
Wish to add dark mode

### ISSUE THREAD

**Issue by chenxuan520** [eolinker/postcat#174]
- Wish to add dark mode, too bright for programmers

**Comment by scarqin** [comment]
@chenxuan520 Thanks for your suggestion, it has been added to roadmap。

**Comment by chenxuan520** [comment]
There is also that the authentication aspect does not feel good enough, I hope there can be a postman-like system, the current export configuration from postman can not recognize authentication, thank you for making such a good software, come on!

**Comment by scarqin** [comment]
@chenxuan520 Do u mean api test authorization？Such as JWT、Basic Auth？

**Comment by scarqin** [comment]
ok，has read comment in other issue,we will consider it.

**Comment by scarqin** [comment]
![image](https://user-images.githubusercontent.com/15225835/205533794-d4f92b69-b384-4077-836b-74f705b6f2e1.png)
@chenxuan520 coming soon！

**Comment by scarqin** [comment]
@chenxuan520 
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/15225835/210088446-eb6ffab6-09bc-4e1d-b502-9478ac67f9be.png">
