### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by Shashengzhe** [eolinker/postcat#212]
### Describe the bug

![image](https://user-images.githubusercontent.com/34408166/209649982-540509b8-b6fa-4d23-a09d-51ef7a270509.png)

![image](https://user-images.githubusercontent.com/34408166/209650079-f1e3843f-9c00-4d61-bee4-71298110c9ac.png)

![image](https://user-images.githubusercontent.com/34408166/209650181-e16d053f-3fff-4b52-a641-6a9108bb4417.png)

### Environment

- http://eoapi.io/

**Comment by scarqin** [comment]
@Shashengzhe 收到反馈，我们看看

**Comment by scarqin** [comment]
dupulicate: https://github.com/eolinker/postcat/issues/142
