### ISSUE TITLE
更新后发现改名了，原来的Server功能怎么不见了？刚在团队这边部署了 突然间整不会了

### ISSUE THREAD

**Issue by davidliudev** [eolinker/postcat#215]
功能改没了吗？
现在好像只有本地功能了？没有协作了？
刚做好调研部署了 团队也都习惯学习了

然后发现原来的eoapi都没了
新版本暂时没找到server

这个规划真的要命 后面不敢用了

**Comment by scarqin** [comment]
@davidliudev 
Remote 在这里，需要配合 https://github.com/eolinker/postcat/releases/tag/Eoapi-v1.11.0 Eoapi 客户端使用，或者 Docker 直接部署 Web。
https://github.com/eolinker/eoapi-remote-server，Remote 已经停止维护了，我们正在用 Java 重构，后续还是会推出协作功能的。

**Comment by davidliudev** [comment]
感谢回复 @scarqin 。
昨天说的有点急还请谅解

其实主要是这个变化有点突然。公司之前调研了之后，觉得eoapi是个不错的客户端，功能和workflow也很不错。执行层面我们已经落实Deploy了服务端EOAPI并且准备开始推新的workflow，然后很多员工反馈说原来的网页端下载变成了Postcat而且无法连接到原来的api server了。

<img width="300" alt="image" src="https://user-images.githubusercontent.com/31893484/211181019-d820d19d-5f7c-400d-a9a0-ed4eb69427ae.png">
(部署的老版本的右上角下载自动变成了postcat，原来是eoapi客户端）

然后才发现原来的remote-server已经archive了，然后整个客户端都改名了。后续的支持也变得不确定了。 
当然我们可以使用旧版本的客户端，但是之前以为会按照旧版本的功能持续迭代，也可以通过社区获得支持。我们也可以给社区提供一些贡献。我们是很希望使用一款开源，尤其是可以self-host的api管理器的。但现在只能重新规划了。

希望后续对于这类重大的更改，能给社区一些deprecation notice period，让大家有充分的时间做准备。

**Comment by scarqin** [comment]
@davidliudev 感谢你的建议，很中肯，确实过渡得比较突然，提醒不够明显。

针对 Self-host 的规划，即使我们使用了 Docker，但团队整体仍然花了蛮多时间去做社区支持/兼容（涉及到部署），所以我们调整在年底调整了方向，希望聚焦核心的功能，优先实现核心功能，满足个人开发者，并使用 SaaS 服务支持和满足团队协作。

再次感谢你的支持，做开源社区的时候总是会面临一些取舍，如果给你带来不便深感抱歉，后续我们会做的更好的，期待重遇。

**Comment by 8pig** [comment]
nest 重构到 java ， 第一版的发布的时间节点大概有排期吗

**Comment by 8pig** [comment]
那服务端重构到java， postcat 会不会改变为 React 或者Vue ？

**Comment by davidliudev** [comment]
我的感觉是项目方不打算继续开源维护服务端而是选择SaaS了。
Correct me if I'm wrong.

其实挺可惜的，市面上还没有比较好的alternative可以做服务器开源。
hoppscotch 据说今年会出Fully Self-host的版本 （现在是基于Google Firebase的）。
后面我们也会关注一下。

**Comment by scarqin** [comment]
@8pig  应该是 1 月 20 号，客户端技术栈不会改动。

**Comment by scarqin** [comment]
@davidliudev You are right.

由于目前 Postcat 项目还在早期，从团队精力角度来说的确难以同时兼顾本地版本和在线版本，考虑到在线版本可以覆盖更多基础用户，因此我们目前选择暂时先专注于在线版本的开发。

**Comment by FromZerozzZ** [comment]
> @davidliudev 我们单位也在选型中，要求支持私有部署，刚好看到了这个，感觉挺适合，可惜项目停了。如果你们的调研结束了，可以分享一下最终的选型方案吗？非常感谢！期间已尝试了yapi、rap2、小幺鸡，但是感觉都不太适用

试下 moyu

**Comment by scarqin** [comment]
@davidliudev Rap2、yapi 哪些功能不满足，可以列出来我分析下推荐个适合你的

**Comment by FromZerozzZ** [comment]
您的邮件已收到，谢谢
