### ISSUE TITLE
When the interface with query parameters is saved, the saved document will display duplicate query parameters

### ISSUE THREAD

**Issue by littlebuzi** [eolinker/postcat#221]
### Describe the bug

When you try to test a url in the test tag, such as: www.eolink.com?a=1
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34567725/215273755-8cdb824c-15f4-432e-a8d1-e4e0808184ed.png">

Then click Save API in the upper right corner, and you will find that the url and query parameters have content
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34567725/215273665-a61a9c98-079d-4d4a-a339-465297f63596.png">

Then save it, and you will find that there are two a. Is there a problem here
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34567725/215273716-643a2afb-8935-4307-9cd2-89e5b8ec1262.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34567725/215273725-be469fd4-4c1b-4d62-b6fb-245393274c59.png">

### Environment

- Version: 1.12.0
- Electron: 21.3.0
- Chromium: 106.0.5249.181
- Node.js: 16.16.0
- V8: 10.6.194.26-electron.0
- OS: Darwin arm64 22.1.0
- Platform: Electron

**Comment by scarqin** [comment]
@littlebuzi Indeed a bug,we will fix it
