### ISSUE TITLE
openapi导出问题，文件里没有api信息

### ISSUE THREAD

**Issue by aaadddfgh** [eolinker/postcat#223]
我在控制台里看了一下，好像原因是数据格式错误，变成了下面这个样子（已隐去部分信息），但还可以正常操作项目
{
    "name": "。。。",
    "workSpaceUuid": "。。。",
    "uuid": "。。。",
    "createTime": 。。。,
    "updateTime": 。。。,
    "id": 1,
    "description": "。。。",
    "projectUuid": "。。。",
    "environmentList": [
           。。。
    ],
    "apiList": [
        。。。 
    ]，
    ”groupList“:[
        。。。
    ]
}
正常的“collections”字段不知道为什么变成“apiList”了，还多了一个“groupList”

### Environment

postcat v0.1.0-beta

**Comment by scarqin** [comment]
@aaadddfgh 无法复现你的情况，你用的是这个插件吗？
<img width="580" alt="image" src="https://user-images.githubusercontent.com/15225835/216733109-d9931499-c8be-4984-a049-3aca41df8a2b.png">
